centroikigai/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from usuario import views as usuario_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', usuario_views.register, name='register'),
    path('profile/', usuario_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='usuario/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='usuario/logout.html'), name='logout'),
    path('', include('ikigai.urls')),
    path('', include('reserva.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ikigai/urls.py
from django.urls import path
from . import views


app_name = 'ikigai'

urlpatterns = [
    path('', views.IkigaiView.as_view(), name='index'),
    path('consulta/', views.consulta, name='consulta'),
]

reserva/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'horas', views.HoraView)
router.register(r'reservas', views.ReservaHoraView)


app_name = 'reserva'

urlpatterns = [
    path('', include(router.urls)),
    path('reserva/', views.ReservaView.as_view(), name='reserva'),
]

ikigai/models.py
from django.db import models

# Create your models here.


class Box(models.Model):
    nombrebox = models.CharField(max_length=25)
    contenido = models.TextField(max_length=170)
    proposito = models.TextField(max_length=150)
    imagen = models.ImageField()

    def __str__(self):
        return self.nombrebox


class Consulta(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField(max_length=50)
    mensaje = models.TextField(max_length=170)

    def __str__(self):
        return self.correo

reserva/models.py
from django.db import models
from ikigai.models import Box
from django.contrib.auth.models import User

# Create your models here.


class Reserva(models.Model):
    idreserva = models.AutoField(primary_key=True)
    fecha = models.DateTimeField()
    #fechaReserva = models.DateField()
    ano = models.IntegerField()
    mes = models.IntegerField()
    dia = models.IntegerField()
    idbox = models.ForeignKey(Box, on_delete=models.SET_NULL, null= True)
    idusuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)


class Horario(models.Model):
    idhorario = models.AutoField(primary_key=True)
    horario = models.CharField(max_length=2)
    valor = models.IntegerField()


class Hora(models.Model):
    idhora = models.AutoField(primary_key=True)
    hora = models.CharField(max_length=13)
    idhorario = models.ForeignKey(Horario, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.hora


class HorasReserva(models.Model):
    idreserva = models.ForeignKey(Reserva, on_delete=models.CASCADE)
    idhora = models.ForeignKey(Hora, on_delete=models.SET_NULL, null=True)


class HorasReservadas(models.Model):
    id = models.BigIntegerField (primary_key=True)
    idbox = models.ForeignKey(Box, on_delete=models.DO_NOTHING, blank=True, null=True)
    ano = models.IntegerField()
    mes = models.IntegerField()
    dia = models.IntegerField()
    idhora = models.ForeignKey(HorasReserva, on_delete=models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'reserva_horasreservadas'


usuario/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile.pics')
    rut = models.CharField(max_length=9)
    celular = models.CharField(max_length=11)
    especialidad = models.CharField(max_length=30)

    def __str__(self):
        return self.user.username

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

usuario/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class RegistroUsuario(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email']


class RegisterProfile(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['rut', 'celular', 'especialidad']


class UserUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['celular', 'image']

ikigai/views.py
from django.shortcuts import render
from .models import Box, Consulta
from django.views import generic
from django.http import HttpResponse

# Create your views here.


class IkigaiView(generic.ListView):
    template_name = 'ikigai/index.html'
    context_object_name = 'box'

    def get_queryset(self):
        return Box.objects.all()


def consulta(request):
    if request.method == 'POST':
        nombre = request.POST.get('nombre', '')
        correo = request.POST.get('correo', '')
        mensaje = request.POST.get('mensaje', '')
        mensaje = Consulta.objects.create(nombre=nombre, correo=correo, mensaje=mensaje)
        mensaje.save()
        return HttpResponse('')

reserva/views.py
from django.shortcuts import render
from django.views import generic
from ikigai.models import Box
from .models import Hora, HorasReservadas
from rest_framework import viewsets
from .serializers import HoraSerializers, ReservaSerializers


class ReservaView(generic.ListView):
    template_name = 'reserva/reserva.html'
    context_object_name = 'boxes'

    def get_queryset(self):
        return Box.objects.all()


class HoraView(viewsets.ModelViewSet):
    queryset = Hora.objects.all()
    serializer_class = HoraSerializers


class ReservaHoraView(viewsets.ModelViewSet):
    queryset = HorasReservadas.objects.all()
    serializer_class = ReservaSerializers

usuario/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import RegistroUsuario, UserUpdateForm, ProfileUpdateForm, RegisterProfile
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = RegistroUsuario(request.POST)
        profile_form = RegisterProfile(request.POST)
        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user_profile = profile_form.save(commit=False)
            user_profile.user = user
            user_profile.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Registro realizado correctamente! Ahora puede iniciar sesion {username}!')
            return redirect('login')
    else:
        form = RegistroUsuario()
        profile_form = RegisterProfile()
    return render(request, 'usuario/register.html', {'form': form,
                                                     'profile_form': profile_form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Perfil actualizado correctamente!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'usuario/profile.html', context)

ikigai/templates/ikigai/base.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">


    <link href="https://fonts.googleapis.com/css?family=Kanit|Oswald|Quicksand|Righteous&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel=icon href="{% static 'images/icono2.png' %}" sizes="any" type="image/svg+xml">
    <title>Ikigai</title>

</head>
<body id="ikigai" data-spy="scroll" data-target=".menu" data-offset="60">
<!--Menu-->
<nav class="navbar navbar-expand-md navbar-dark sticky-top">
    <a class="brand mr-2" href="#ikigai"><img src="{% static 'images/icono.png' %}" alt="logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse menu" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="#nosotros">Nosotros</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#servicios">Servicios</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#box">Box</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#valores">Valores</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#contacto">Contacto</a>
            </li>
            <li class="nav-item">
                <a class="nav-link reserva" href="{% url 'reserva:reserva' %}">Reservas</a>
            </li>
        </ul>
        <form class="form-inline">
            {% if user.is_authenticated %}
                <a class="btn btn-sm btn-outline-light mr-2" href="{% url 'profile' %}">Perfil</a>
                <a class="btn btn-sm btn-outline-light" href="{% url 'logout' %}">Cerrar Sesion</a>
            {% else %}
                <a class="btn btn-sm btn-outline-light" href="{% url 'login' %}">Iniciar Sesion</a>
            {% endif %}
        </form>
    </div>
</nav>
<!--/Menu-->

{% block content %}

{% endblock %}

<!--Footer-->
<footer class="footer text-center">
    <div class="pt-3">
        <a href="#ikigai">
            <i class="fas fa-angle-up "></i>
        </a>
    </div>
    <ul class="pt-3 social">
        <li class="list-inline-item">
            <p>Siguenos en</p>
        </li>
        <li class="list-inline-item">
            <a href="https://www.facebook.com/Centro-Ikigai-263378267525965/?ref=settings" class="btn-floating btn-fb mx-1">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="https://www.instagram.com/centroikigai/" class="btn-floating btn-dribbble mx-1">
                <i class="fab fa-instagram"></i>
            </a>
        </li>
    </ul>
    <div class="footer-copyright p-3">Todos los derechos reservados | Centro Ikigai 2018
    </div>
</footer>
<!--/Footer-->


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
-->
<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>

<!--
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
-->
<script src="{% static 'js/popper.min.js' %}"></script>

<!--
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
-->
<script src="{% static 'js/bootstrap.min.js' %}"></script>


<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>

</body>
</html>

reserva/templates/reserva/reserva.html
<!DOCTYPE html>
<html lang="es">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Kanit|Oswald|Quicksand|Righteous&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <link rel=icon href="{% static 'images/icono2.png' %}" sizes="any" type="image/svg+xml">

    <title>Ikigai</title>
</head>

<body id="ikigai" data-spy="scroll" data-target=".menu" data-offset="60">
<!--Menu-->
<nav class="navbar navbar-expand-md navbar-dark sticky-top">
    <a class="brand mr-2" href="#ikigai"><img src="{% static 'images/icono.png' %}" alt="logo"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse menu" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ikigai:index' %}">Ikigai</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'reserva:reserva' %}">Reservas</a>
            </li>
        </ul>
        <form class="form-inline">
            {% if user.is_authenticated %}
                <a class="btn btn-sm btn-outline-light mr-2" href="{% url 'profile' %}">Perfil</a>
                <a class="btn btn-sm btn-outline-light" href="{% url 'logout' %}">Cerrar Sesion</a>
            {% else %}
                <a class="btn btn-sm btn-outline-light" href="{% url 'login' %}">Iniciar Sesion</a>
            {% endif %}
        </form>
    </div>
</nav>
<!--/Menu-->

{% if messages %}
    {% for message in messages %}
        <div class="profile-alert alert alert-{{ message.tags }}" style="font-size: 2.5vmin;">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

{% block content %}

<!--Box-->
<div class="section shadow-lg" id="box">
    <h2 class="title text-center">Reservas</h2>
    <div class="row justify-content-center">
        {% if boxes %}
            {% for box in boxes %}
                <div class="col-sm-6 col-md-4 col-lg-3 {{ box.nombrebox }}">
                    <div class="box_grid shadow">
                        <figure class="block-reveal">
                            <img src="{{ box.imagen.url }}" class="img-fluid" alt="">
                            <div class="price">{{ box.nombrebox }}</div>
                        </figure>
                        <div class="wrapper">
                            <small>Equipamiento</small>
                            <p>{{ box.contenido }}</p>
                            <small>Espacial para:</small>
                            <p>{{ box.proposito }}</p>
                        </div>
                        <ul>
                            <li>
                                <div class="btn-reserva" id="{{ box.id }}" data-toggle="modal"
                                     data-target="#{{ box.nombrebox }}">Reservar
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>

                <!--Modal-->
                <div id="{{ box.nombrebox }}" class="modal fade" tabindex="-1" role="dialog"
                     aria-labelledby="gridModalLabel" style="display: none;" aria-hidden="true" data-backdrop="static"
                     data-keyboard="false">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="gridModalLabel">{{ box.nombrebox }}</h5>
                            </div>
                            <div class="modal-body">
                                <div class="container-fluid bd-example-row">
                                    <div class="row">
                                        <div class="col-12 calendar" id="{{ box.id }}"><!--calendario--> </div>
                                    </div>
                                </div>
                            </div>
                            <div class="modal-footer">
                                <div class="btn-cancelar btn-canReserva" data-dismiss="modal" id="{{ box.id }}">
                                    Cancelar
                                </div>
                                <div class="btn-disabled btn-confirmar btn-conReserva" id="{{ box.id }}">
                                    Confirmar
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--Fin Modal-->

            {% endfor %}
        {% else %}
            <p>Agregar Box</p><i class="far fa-grin-beam-sweat"></i>
        {% endif %}
    </div>
</div>
<!--/Box-->

{% endblock %}

</body>

<!--Footer-->
<footer class="footer text-center">
    <div class="pt-3">
        <a href="#ikigai">
            <i class="fas fa-angle-up "></i>
        </a>
    </div>
    <ul class="pt-3 social">
        <li class="list-inline-item">
            <p>Siguenos en</p>
        </li>
        <li class="list-inline-item">
            <a href="https://www.facebook.com/Centro-Ikigai-263378267525965/?ref=settings"
               class="btn-floating btn-fb mx-1">
                <i class="fab fa-facebook-f"></i>
            </a>
        </li>
        <li class="list-inline-item">
            <a href="https://www.instagram.com/centroikigai/" class="btn-floating btn-dribbble mx-1">
                <i class="fab fa-instagram"></i>
            </a>
        </li>
    </ul>
    <div class="footer-copyright p-3">Todos los derechos reservados | Centro Ikigai 2018</div>
</footer>
<!--/Footer-->


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
-->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous">
</script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<!--
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
-->

<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
<!--<script src="{% static 'js/popper.min.js' %}"></script>-->
<script src="{% static 'js/bootstrap.min.js' %}"></script>

<script src="{% static 'js/base.js' %}"></script>
<script src="{% static 'js/calendar.js' %}"></script>
<script src="{% static 'js/jquery.min.js' %}"></script>




usuario/templates/usuario/login.html
{% extends 'reserva/reserva.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10 col-md-6 col-lg-4 content-section shadow">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Bienvenido</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Ingresar</button>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Necesita una cuenta? <a class="ml-2" href="{% url 'register' %}">Regístrese</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/logout.html
{% extends 'reserva/reserva.html' %}
{% block content %}
    <div class="text-center logout">
        <p>Sesion cerrada correctamente</p>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a href="{% url 'login' %}">Iniciar Sesion Nuevamente</a>
            </small>
        </div>
    </div>
{% endblock %}

usuario/templates/usuario/profile.html
{% extends 'reserva/reserva.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10 col-md-6 col-lg-4 content-section shadow">
                <div class="media">
                    <img class="rounded-circle account-img" src="{{ user.profile.image.url }}" alt="">
                    <div class="media-body">
                        <h2 class="">{{ user.username }}</h2>
                        <p class="text-secondary user-mail" style="font-size: 2.5vmin">{{ user.email }}</p>
                    </div>
                </div>
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 register">Perfil de Usuario</legend>
                        {{ u_form|crispy }}
                        {{ p_form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Actualizar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

usuario/templates/usuario/register.html
{% extends 'reserva/reserva.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10 col-md-6 col-lg-4 content-section shadow">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Bienvenido</legend>
                        {{ form|crispy }}
                        {{ profile_form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">Aceptar</button>
                    </div>
                </form>
                <div class="border-top pt-3">
                    <small class="text-muted">
                        Ya tienes una cuenta? <a class="ml-2" href="{% url 'login' %}">Iniciar Sesion</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
{% endblock %}